version: "3.7"
services: 
  web:
    build: . 
    ports:
      - "8080:5000"

  mongodb: 
    image: "mongo:latest"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017