version: '3.3'

services:
 backend:
  container_name: PYTHON-API-BACKEND
  build: .
  command: python3 -u app.py && gunicorn -w 1 -b :8080 app:app 
  ports:
    - 8080:8080
  volumes:
    - .:/opt/projetos/dev/api
  links:
    - db
 db:
  image: mongo:latest
  container_name: MONGO-API-BACKEND
  ports:
    - "27017:27017"
  volumes:
    - .:/opt/projetos/dev/api/data 