services:   
  app:     
    build: .     
    command: python -u app.py     
    ports:       
      - "8080:5000"    
    volumes:       
      - .:/app    
    links:       
      - db    
  db:       
    image: mongo:latest            
    environment:         
      - MONGO_INITDB_DATABASE=flask_db         
  